- hosts: localhost
  gather_facts: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    go_version: '1.19.1'
  pre_tasks:
    - name: Update Package Manager - Arch - Pacman -Syu
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - install
        - core
      when: ansible_os_family == "Archlinux"

    - name: Update Package Manager - Debian - Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
      when: ansible_os_family == "Debian"

  tasks:
    # - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/fonts-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/go-setup.yml
    - include: tasks/go-packages.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/alacritty-build.yml
    #   - include: tasks/slack-setup.yml
    - include: tasks/scripts-and-utils-setup.yml
    - include: tasks/dev-setup.yml
    - include: tasks/notes-setup.yml
    - include: tasks/timers-setup.yml
    - include: tasks/nvim-setup.yml
    #   - include: tasks/brave.yml
    #   - include: tasks/debugger.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tmux-setup.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/lsp-setup.yml
