- hosts: localhost
  name: New System Setup
  gather_facts: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    go_version: '1.19.1'
    golangci_lint_version: '1.49.0'
    node_version: '16'

  pre_tasks:
    - name: Update Package Manager - Arch - Pacman -Syu
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - install
        - core
      when: ansible_os_family == "Archlinux"

    - name: Update Package Manager - Debian - Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
      when: ansible_os_family == "Debian"

    - name: Update Homebrew on Mac
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: ansible_distribution == 'MacOSX'

  roles:
    - role: nix-install

  collections:
    - community.general.snap
    - community.general.flatpak
    - community.general.pacman
    - community.general.homebrew

  tasks:
    - include: tasks/alacritty-build.yml
    - include: tasks/bluetooth-setup.yml
    - include: tasks/cargo-packages.yml
    - include: tasks/cleanup.yml
    - include: tasks/core-setup.yml
    - include: tasks/custom-services.yml
    - include: tasks/debuggers.yml
    - include: tasks/dev-setup.yml
    - include: tasks/dmscripts-setup.yml
    - include: tasks/docker.yml
    - include: tasks/dotfiles.yml
    # - include: tasks/etcher.yml
    - include: tasks/fonts-setup.yml
      #   - include: tasks/games.yml
    - include: tasks/flatpak.yml
    - include: tasks/snap-packages.yml
    - include: tasks/git-setup.yml
    - include: tasks/go-packages.yml
    - include: tasks/go-setup.yml
    - include: tasks/pip-packages.yml
    - include: tasks/i3lock-color.yml
    - include: tasks/lsp-setup.yml
    - include: tasks/mpd-setup.yml
    - include: tasks/nix-packages.yml
    - include: tasks/node-setup.yml
    - include: tasks/notes-setup.yml
    - include: tasks/notifications-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/obs.yml
    - include: tasks/productivity-tools.yml
    # - include: tasks/qtile-setup.yml
    - include: tasks/scripts-and-utils-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/themes.yml
    # - include: tasks/thunderbird.yml
    - include: tasks/timers-setup.yml
    - include: tasks/tmux-setup.yml
    - include: tasks/zoom.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/update-all-packages.yml
    - include: tasks/mac-setup.yml
