- hosts: localhost
  name: New System Setup
  gather_facts: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    go_version: '1.19.1'
    golangci_lint_version: '1.49.0'
    node_version: '16'

  pre_tasks:
    - name: Update Package Manager - Arch - Pacman -Syu
      become: true
      ansible.builtin.pacman:
        update_cache: true
        upgrade: true
      tags:
        - install
        - core
      when: ansible_os_family == "Archlinux"

    - name: Update Package Manager - Debian - Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
      when: ansible_os_family == "Debian"

  tasks:
    # - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/fonts-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/ranger-setup.yml
    - include: tasks/bluetooth-setup.yml
    - include: tasks/qtile-setup.yml
    - include: tasks/go-setup.yml
    - include: tasks/go-packages.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/alacritty-build.yml
    - include: tasks/slack-setup.yml
    - include: tasks/scripts-and-utils-setup.yml
    - include: tasks/dmscripts-setup.yml
    - include: tasks/dev-setup.yml
    - include: tasks/notes-setup.yml
    - include: tasks/timers-setup.yml
    - include: tasks/notifications-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/brave.yml
    - include: tasks/docker.yml
    - include: tasks/beekeeper.yml
    - include: tasks/discord.yml
    - include: tasks/zoom.yml
    - include: tasks/obs.yml
    - include: tasks/thunderbird.yml
    - include: tasks/audacity.yml
    - include: tasks/etcher.yml
    - include: tasks/debuggers.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tmux-setup.yml
    - include: tasks/mpd-setup.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/lsp-setup.yml
    - include: tasks/games.yml
