#
- name: clone alacritty from github
  ansible.builtin.git:
    repo: 'git@github.com:alacritty/alacritty.git'
    dest: '{{ home }}/alacritty/'
  tags:
    - install
    - alacritty

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - install
    - alacritty

- name: download installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - alacritty

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - install
    - alacritty

- name: install rust compiler with rustup
  when: cargo_exists is failed
  shell:
    cmd: rustup override set stable && rustup update stable
    chdir: '{{ home }}/alacritty/'
  tags:
    - install
    - alacritty

- name: build the super duper fast terminal
  shell:
    cmd: cargo build --release --no-default-features --features=x11
    chdir: '{{ home }}/alacritty/'
  tags:
    - install
    - alacritty

#If all goes well, this should place a binary at target/release/alacritty.

# Post installation
#
# if `infocmp alacritty` returns without errors,
# terminfo is installed. Otherwise install it with
# sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
- name: install terminfo
  become: true
  shell:
    cmd: tic -xe alacritty,alacritty-direct '{{ home }}/alacritty/extra/alacritty.info'
  tags:
    - install
    - alacritty

# Desktop Entry
# sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
#
- name: copy bin to path
  become: true
  copy:
    src: '{{ home }}/alacritty/target/release/alacritty'
    dest: '/usr/local/bin'
    mode: 0775
  tags:
    - install
    - alacritty

# sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
- name: desktop file install
  become: true
  copy:
    src: '{{ home }}/alacritty/extra/logo/alacritty-term.svg'
    dest: '/usr/share/pixmaps/Alacritty.svg'
    mode: 0775
  tags:
    - install
    - alacritty
      #
# sudo desktop-file-install extra/linux/Alacritty.desktop
- name: run desktop-file-install
  become: true
  shell:
    cmd: desktop-file-install {{ home }}/alacritty/extra/linux/Alacritty.desktop
  tags:
    - install
    - alacritty

# sudo update-desktop-database
- name: update desktop database
  become: true
  shell:
    cmd: update-desktop-database
  tags:
    - install
    - alacritty

# Man Page
#
# sudo mkdir -p /usr/local/share/man/man1
# gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
# gzip -c extra/alacritty-msg.man | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
#
# ZSH Completions
#
# To install the completions for zsh, you can place the extra/completions/_alacritty file in any directory referenced by $fpath.
#
# If you do not already have such a directory registered through your ~/.zshrc, you can add one like this:
#
# mkdir -p ${ZDOTDIR:-~}/.zsh_functions
# echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc
# Then copy the completion file to this directory:
#
# cp extra/completions/_alacritty ${ZDOTDIR:-~}/.zsh_functions/_alacritty
