- name: Keyrings - create folder if it doesn't exist
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - beekeeper
  when: ansible_os_family == "Debian"

- name: Beekeeper - Add key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.beekeeperstudio.io/beekeeper.key
    state: present
  tags:
    - beekeeper
  when: ansible_os_family == "Debian"

- name: Beekeeper - Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb https://deb.beekeeperstudio.io stable main'
    state: present
    filename: docker
  when: ansible_os_family == "Debian"
  tags:
    - beekeeper

- name: Beekeeper apt installation
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - beekeeper-studio
  tags:
    - beekeeper
  when: ansible_os_family == "Debian"

- name: Install Beekeeper from the AUR
  ansible.builtin.command: paru --noconfirm -S beekeeper-studio-bin
  tags:
    - beekeeper
  when: ansible_os_family == "Archlinux"
