- name: Required libraries for brave
  become: true
  ansible.builtin.apt:
    name: ['curl', 'apt-transport-https']
  tags:
    - brave
  when: ansible_os_family == "Debian"

- name: Brave Browser archive-keyring.gpg download
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: 0775
  tags:
    - brave
  when: ansible_os_family == "Debian"

- name: Brave Browser PPA setting
  become: true
  ansible.builtin.command: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
  when: ansible_os_family == "Debian"

- name: Brave Browser apt installation
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: brave-browser
  tags:
    - brave
  when: ansible_os_family == "Debian"

- name: Brave Browser pacman installation
  become: true
  ansible.builtin.pacman:
    name: brave-bin
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"
