- name: Install System Packages 1 - Arch (base-devel, cmake, pkgconf)
  become: true
  ansible.builtin.pacman:
    name: ['base-devel', 'cmake', 'pkgconf']
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 2 - Arch (lua, libtool, gettext)
  become: true
  ansible.builtin.pacman:
    name: ['lua', 'libtool', 'gettext']
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 3 - Arch
  become: true
  ansible.builtin.pacman:
    name:
      [
        'picom',
        'paru-bin',
        'curl',
        'wget',
        'htop',
        'lsof',
        'ccache',
        'ninja',
        'python-pip',
        'python',
        'dconf-editor',
        'nvidia-settings',
        'pavucontrol',
        'moreutils',
        'clang',
        'pandoc',
        'figlet',
        'cowsay',
        'fortune-mod',
        'nitrogen',
        'freetype2',
        'make',
        'libxcb',
        'libxkbcommon',
        'pkg-config',
        'fontconfig',
        'brave-bin',
        'networkmanager',
        'networkmanager-openvpn',
        'network-manager-applet',
        'cups',
        'radiotray',
      ]
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 1 - Debian (build-essential, cmake, pkg-config, pthread)
  become: true
  ansible.builtin.apt:
    name: ['build-essential', 'cmake', 'pkg-config', 'libpthread-stubs0-dev']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 2 - Debian (lua, libtool, libtool-bin, gettext)
  become: true
  ansible.builtin.apt:
    name: ['lua5.1', 'libtool', 'libtool-bin', 'gettext']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 3 - Debian (the rest)
  become: true
  ansible.builtin.apt:
    name:
      [
        'compton',
        'curl',
        'wget',
        'htop',
        'lsof',
        'ccache',
        'ninja-build',
        'python3-pip',
        'python3',
        'dconf-editor',
        'nvidia-settings',
        'pavucontrol',
        'moreutils',
        'clangd',
        'libx11-dev',
        'libxinerama-dev',
        'libxft-dev',
        'apt-file',
        'pandoc',
        'libxrandr-dev',
        'libxpm-dev',
        'figlet',
        'cowsay',
        'nitrogen',
        'fortune',
        'libfreetype6-dev',
        'libfontconfig1-dev',
        'libxcb-xfixes0-dev',
        'libxkbcommon-dev ',
        'network-manager',
        'cups',
        'network-manager-openvpn',
        'snapd',
        'aptitude',
        'netrw',
      ]
  tags:
    - install
    - core
  when: ansible_os_family == "Debian"

# - name: Install Flatpack - Debian
#   become: true
#   ansible.builtin.apt:
#     name: flatpack
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"
#
# - name: Add Flathub repo to flatpack
#   ansible.builtin.command: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"

- name: Install Clang - Debian
  become: true
  ansible.builtin.apt:
    name: ['clang', 'clang-11', 'clang-12', 'clangd', 'clangd-11', 'clangd-12']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

# - name: Set up radiotray lite ppa
#   become: true
#   ansible.builtin.apt_repository:
#     repo: ppa:nilarimogard/webupd8
#     state: present
#     update_cache: True
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"
#
# - name: Install radiotray lite
#   become: true
#   ansible.builtin.apt:
#     name:
#       - radiotray-lite
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"

- name: Install commonly named packages
  become: true
  ansible.builtin.package:
    name:
      - acpi
      - arandr
      - fzf
      - vlc
      - rhythmbox
      - xdg-utils
      - ripgrep
      - xfce4-power-manager
      - font-manager
      - tree
      - unzip
      - unrar
      - nmap
      - autorandr
  tags:
    - install
    - neovim
    - alacritty
    - core

# start and enable networkmanager
- name: Start and ennable networkmanager. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    state: started
    name: NetworkManager
    enabled: true
    masked: false
  tags:
    - install
    - core

# start and enable cups
- name: Start and enable cups. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    name: cups.socket
    enabled: true
    masked: false
  tags:
    - install
    - core
