- name: Install System Packages 1 - Arch (base-devel, cmake, pkgconf)
  become: true
  ansible.builtin.pacman:
    name: ['base-devel', 'cmake', 'pkgconf']
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 2 - Arch (lua, libtool, gettext)
  become: true
  ansible.builtin.pacman:
    name: ['lua', 'libtool', 'gettext']
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 3 - Arch
  become: true
  ansible.builtin.pacman:
    name:
      [
        'brave-bin',
        'ccache',
        'clang',
        'cowsay',
        'cups',
        'curl',
        'dconf-editor',
        'figlet',
        'fontconfig',
        'fortune-mod',
        'freetype2',
        'htop',
        'libxcb',
        'libxkbcommon',
        'lsof',
        'make',
        'moreutils',
        'networkmanager',
        'network-manager-applet',
        'networkmanager-openvpn',
        'ninja',
        'nitrogen',
        'nvidia-settings',
        'pandoc',
        'paru-bin',
        'pavucontrol',
        'picom',
        'pkg-config',
        'python',
        'python-pip',
        'stow',
        'wget',
        'virtualbox',
        'virtualbox-host-modules-arch',
        'libgirepository',
      ]
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 1 - Debian (build-essential, cmake, pkg-config, pthread)
  become: true
  ansible.builtin.apt:
    name: ['build-essential', 'cmake', 'pkg-config', 'libpthread-stubs0-dev']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 2 - Debian (lua, libtool, libtool-bin, gettext)
  become: true
  ansible.builtin.apt:
    name: ['lua5.1', 'libtool', 'libtool-bin', 'gettext']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 3 - Debian (the rest)
  become: true
  ansible.builtin.apt:
    name:
      [
        'apt-file',
        'aptitude',
        'ccache',
        'clangd',
        'compton',
        'cowsay',
        'cups',
        'curl',
        'dconf-editor',
        'figlet',
        'fortune',
        'htop',
        'libfontconfig1-dev',
        'libfreetype6-dev',
        'libx11-dev',
        'libxcb-xfixes0-dev',
        'libxft-dev',
        'libxinerama-dev',
        'libxkbcommon-dev ',
        'libxpm-dev',
        'libxrandr-dev',
        'lsof',
        'moreutils',
        'netrw',
        'network-manager',
        'network-manager-openvpn',
        'ninja-build',
        'nitrogen',
        'nvidia-settings',
        'pandoc',
        'pavucontrol',
        'python3',
        'python3-pip',
        'wget',
        'libkrb5-dev',
        'libsystemd-dev',
        'mtp-tools',
        'virtualbox',
        'libgirepository1.0-dev',
      ]
  tags:
    - install
    - core
  when: ansible_os_family == "Debian"

- name: Install Clang - Debian
  become: true
  ansible.builtin.apt:
    name: ['clang', 'clang-11', 'clang-12', 'clangd', 'clangd-11', 'clangd-12']
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install commonly named packages
  become: true
  ansible.builtin.package:
    name:
      - acpi
      - arandr
      - autorandr
      - ffmpegthumbnailer
      - font-manager
      - fzf
      # - imwheel # needs to be configured - `bash <(curl -s http://www.nicknorton.net/mousewheel.sh)` https://dev.to/bbavouzet/ubuntu-20-04-mouse-scroll-wheel-speed-536o
      - lxinput
      - nmap
      - qalculate-gtk
      # - rhythmbox
      - ripgrep
      - tree
      - unrar
      - unzip
      - vlc
      - xdg-utils
      - xfce4-power-manager
      - pinta
      - sshfs
      - android-sdk
      - redshift
  when: ansible_distribution != 'MacOSX'
  tags:
    - install
    - neovim
    - alacritty
    - core

# start and enable networkmanager
- name: Start and ennable networkmanager. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    state: started
    name: NetworkManager
    enabled: true
    masked: false
  tags:
    - install
    - core

# start and enable cups
- name: Start and enable cups. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    name: cups.socket
    enabled: true
    masked: false
  tags:
    - install
    - core
