- name: Install System Packages 1 - Arch (base-devel, cmake, pkgconf)
  become: true
  ansible.builtin.pacman:
    name: ["base-devel", "cmake", "pkgconf"]
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 2 - Arch (lua, libtool, gettext)
  become: true
  ansible.builtin.pacman:
    name: ["lua", "libtool", "gettext"]
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 3 - Arch
  become: true
  ansible.builtin.pacman:
    name:
      [
        "brave-bin",
        "ccache",
        "clang",
        "cowsay",
        "cups",
        "curl",
        "dconf-editor",
        "figlet",
        "fontconfig",
        "fortune-mod",
        "freetype2",
        "htop",
        "libxcb",
        "libxkbcommon",
        "lsof",
        "make",
        "moreutils",
        "networkmanager",
        "network-manager-applet",
        "networkmanager-openvpn",
        "ninja",
        "nitrogen",
        "nvidia-settings",
        "pandoc",
        "paru-bin",
        "pavucontrol",
        "picom",
        "pkg-config",
        "python",
        "python-pip",
        "radiotray",
        "stow",
        "wget",
      ]
    state: present
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Archlinux"

- name: Install System Packages 1 - Debian (build-essential, cmake, pkg-config, pthread)
  become: true
  ansible.builtin.apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 2 - Debian (lua, libtool, libtool-bin, gettext)
  become: true
  ansible.builtin.apt:
    name: ["lua5.1", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

- name: Install System Packages 3 - Debian (the rest)
  become: true
  ansible.builtin.apt:
    name:
      [
        "apt-file",
        "aptitude",
        "ccache",
        "clangd",
        "compton",
        "cowsay",
        "cups",
        "curl",
        "dconf-editor",
        "figlet",
        "fortune",
        "htop",
        "libfontconfig1-dev",
        "libfreetype6-dev",
        "libx11-dev",
        "libxcb-xfixes0-dev",
        "libxft-dev",
        "libxinerama-dev",
        "libxkbcommon-dev ",
        "libxpm-dev",
        "libxrandr-dev",
        "lsof",
        "moreutils",
        "netrw",
        "network-manager",
        "network-manager-openvpn",
        "ninja-build",
        "nitrogen",
        "nvidia-settings",
        "pandoc",
        "pavucontrol",
        "python3",
        "python3-pip",
        "snapd",
        "trash-cli",
        "volumeicon-alsa",
        "wget",
      ]
  tags:
    - install
    - core
  when: ansible_os_family == "Debian"

# - name: Install Flatpack - Debian
#   become: true
#   ansible.builtin.apt:
#     name: flatpack
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"
#
# - name: Add Flathub repo to flatpack
#   ansible.builtin.command: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"

- name: Install Clang - Debian
  become: true
  ansible.builtin.apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - install
    - neovim
    - alacritty
    - core
  when: ansible_os_family == "Debian"

# - name: Set up radiotray lite ppa
#   become: true
#   ansible.builtin.apt_repository:
#     repo: ppa:nilarimogard/webupd8
#     state: present
#     update_cache: True
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"
#
# - name: Install radiotray lite
#   become: true
#   ansible.builtin.apt:
#     name:
#       - radiotray-lite
#   tags:
#     - install
#     - neovim
#     - alacritty
#     - core
#   when: ansible_os_family == "Debian"

- name: Install commonly named packages
  become: true
  ansible.builtin.package:
    name:
      - acpi
      - arandr
      - fzf
      - vlc
      # - rhythmbox
      - xdg-utils
      - ripgrep
      - xfce4-power-manager
      - font-manager
      - tree
      - unzip
      - unrar
      - nmap
      - autorandr
      - lxinput
      - qalculate-gtk
      - ffmpegthumbnailer
      # - imwheel # needs to be configured - `bash <(curl -s http://www.nicknorton.net/mousewheel.sh)` https://dev.to/bbavouzet/ubuntu-20-04-mouse-scroll-wheel-speed-536o
  tags:
    - install
    - neovim
    - alacritty
    - core

# start and enable networkmanager
- name: Start and ennable networkmanager. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    state: started
    name: NetworkManager
    enabled: true
    masked: false
  tags:
    - install
    - core

# start and enable cups
- name: Start and enable cups. Ensure it is not masked.
  become: true
  ansible.builtin.systemd:
    name: cups.socket
    enabled: true
    masked: false
  tags:
    - install
    - core
