- name: Install System Packages 1 (base-devel, cmake, pkgconf)
  become: yes
  pacman:
    name: ["base-devel", "cmake", "pkgconf"]
    state: present
  tags:
    - install
    - neovim
    - core
#  libpthread-stubs available in AUR
#
- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  become: yes
  pacman:
    name: ["lua", "unzip", "libtool", "gettext"]
    state: present
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3
  become: yes
  pacman:
    name: ["picom", "curl", "htop", "go", "lsof", "qtile", "ccache", "ninja", "python-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "clang"]
    state: present
  tags:
    - install
    - neovim
    - core
 
#
# - name: SHELL COMMADN
#   become: -- yes/no
#   shell: <COMMAND>
#   tags:
#     - install
#     - neovim
#     - core
#
#
