- name: Remove old versions of docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags:
    - docker
  when: ansible_os_family == "Debian"

- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Docker - Add signing key
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Docker - Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable'
    state: present
    filename: docker
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Install Docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-registry
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Install docker
  community.general.homebrew:
    name: docker
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

- name: Install docker-machine
  community.general.homebrew:
    name: docker-machine
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

- name: Install docker compose
  community.general.homebrew:
    name: docker-compose
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

# this is a dependency here, but can't istall for arm using brew
# - name: Install VirtualBox
#   ansible.builtin.command: 'brew install --cask virtualbox'
#   when: ansible_distribution == 'MacOSX'
#   tags:
#     - docker
#     - mac-setup
#

- name: Create VirtualBox Driver for docker-machine
  ansible.builtin.command: 'docker-machine create --driver virtualbox default'
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

- name: Restart docker-machine
  ansible.builtin.command: 'docker-machine restart'
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

- name: Regenerate Certs and Restart
  ansible.builtin.shell: docker-machine regenerate-certs && docker-machine restart
  when: ansible_distribution == 'MacOSX'
  tags:
    - docker
    - mac-setup

- name: Install Docker - Common
  become: true
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution != 'MacOSX'
  tags:
    - docker

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    append: yes
    groups: docker
  tags:
    - docker

- name: Start and enable docker daemon
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true
    masked: false
  when: ansible_distribution != 'MacOSX'
  tags:
    - docker
