- name: Remove old versions of docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags:
    - docker
  when: ansible_os_family == "Debian"

- name: Install apt-transport-https
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Docker - Add signing key
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Docker - Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Install Docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-registry
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Install Docker - Common
  become: true
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    append: yes
    groups: docker
  tags:
    - docker

- name: Start and enable docker daemon
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true
    masked: false
  tags:
    - docker
