- name: Install docker - Arch
  become: true
  ansible.builtin.pacman:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker
  when: ansible_os_family == "Archlinux"

- name: Remove old versions of docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags:
    - docker
  when: ansible_os_family == "Debian"

- name: Install dependencies - Debian
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  tags:
    - docker
  when: ansible_os_family == "Debian"


- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
  when: ansible_os_family == "Debian"

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker
  when: ansible_os_family == "Debian"


- name: Docker apt installation
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  tags:
    - docker
  when: ansible_os_family == "Debian"
