- name: Install docker - Arch
  become: true
  ansible.builtin.pacman:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker
  when: ansible_os_family == "Archlinux"

- name: Remove old versions of docker - Debian
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags:
    - docker
  when: ansible_os_family == "Debian"

- name: Install apt-transport-https
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Add signing key
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - docker

- name: adding user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    append: yes
    groups: docker
