- name: Install stow
  become: true
  ansible.builtin.package:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow

- name: Dotfiles exists
  ansible.builtin.stat:
    path: '{{ home }}/.dotfiles'
  register: dotfiles
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/dotfiles.git'
    bare: false
    dest: '{{ home }}/.dotfiles'
  tags:
    - install
    - dotfiles
    - stow
  when: not dotfiles.stat.exists

- name: Stow dotfiles
  ansible.builtin.command: cd $HOME/.dotfiles && stow -R .
  tags:
    - install
    - dotfiles
    - stow
