- name: install agave nerd font
  ansible.builtin.shell:
    cmd: curl -fLo "agave regular Nerd Font Complete.ttf"   https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Agave/complete/agave%20regular%20Nerd%20Font%20Complete.ttf
    chdir: '{{ home }}/.fonts'
  tags:
    - install
    - fonts

- name: install big blue terminal font
  ansible.builtin.shell:
    cmd: curl -fLo "BigBlue TerminalPlus Nerd Font Complete.TTF"   https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/BigBlueTerminal/complete/BigBlue%20TerminalPlus%20Nerd%20Font%20Complete.TTF
    chdir: '{{ home }}/.fonts'
  tags:
    - install
    - fonts

- name: update font cache
  ansible.builtin.shell:
    cmd: fc-cache -fv
    chdir: '{{ home }}/.fonts'
  tags:
    - install
    - fonts
