- name: download golang tar file
  shell:
    cmd: 'wget https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz'
    chdir: '/tmp/'
  tags:
    - install
    - core
    - go
  when: ansible_os_family == "Debian"

- name: extract tar file
  become: true
  shell:
    cmd: 'tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz'
    chdir: '/tmp/'
  tags:
    - install
    - core
    - go
  when: ansible_os_family == "Debian"

- name: remove tar file
  ansible.builtin.file:
    path: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    state: absent
  tags:
    - install
    - core
    - go
  when: ansible_os_family == "Debian"

- name: Install go
  community.general.homebrew:
    name: go
    state: present
  tags:
    - go
    - mac-setup
  when: ansible_distribution == 'MacOSX'
