- name: Install i3
  ansible.builtin.command: 'nix-env -iA nixpkgs.i3'
  tags:
    - install
    - nix-packages

- name: Install volumeicon
  ansible.builtin.command: 'nix-env -iA nixpkgs.volumeicon'
  tags:
    - install
    - nix-packages

- name: Install trash-cli
  ansible.builtin.command: 'nix-env -iA nixpkgs.trash-cli'
  tags:
    - install
    - nix-packages

# other versions of stow are broken
- name: Install stow
  ansible.builtin.command: 'nix-env -iA stow -f https://github.com/NixOS/nixpkgs/archive/4599f2bb9a5a6b1482e72521ead95cb24e0aa819.tar.gz'
  tags:
    - install
    - nix-packages
  when: ansible_os_family == "Debian"

- name: Install brave
  ansible.builtin.command: 'nix-env -iA nixpkgs.brave'
  tags:
    - install
    - nix-packages
  when: ansible_os_family == "Debian"

- name: Install chafa
  ansible.builtin.command: 'nix-env -iA nixpkgs.chafa'
  tags:
    - install
    - nix-packages

- name: Install fontpreview
  ansible.builtin.command: 'nix-env -iA nixpkgs.fontpreview'
  tags:
    - install
    - nix-packages

- name: Install minikube
  ansible.builtin.command: 'nix-env -iA nixpkgs.minikube'
  tags:
    - install
    - nix-packages

- name: Install beekeeper
  ansible.builtin.command: 'nix-env -iA nixpkgs.beekeeper-studio'
  tags:
    - install
    - nix-packages

- name: Install chrome
  ansible.builtin.shell: 'export NIXPKGS_ALLOW_UNFREE=1 && nix-env -iA nixpkgs.google-chrome'
  tags:
    - install
    - nix-packages

- name: Install discord
  ansible.builtin.shell: 'export NIXPKGS_ALLOW_UNFREE=1 && nix-env -iA nixpkgs.discord'
  tags:
    - install
    - nix-packages

- name: Install audacity
  ansible.builtin.command: 'nix-env -iA nixpkgs.audacity'
  tags:
    - install
    - nix-packages

- name: Install slack
  ansible.builtin.shell: 'export NIXPKGS_ALLOW_UNFREE=1 && nix-env -iA nixpkgs.slack'
  tags:
    - install
    - nix-packages

- name: Install postman
  ansible.builtin.shell: 'export NIXPKGS_ALLOW_UNFREE=1 && nix-env -iA nixpkgs.postman'
  tags:
    - install
    - nix-packages

- name: Install altair graphql editor
  ansible.builtin.command: 'nix-env -iA nixpkgs.altair'
  tags:
    - install
    - nix-packages

- name: Install radiotray-ng
  ansible.builtin.command: 'nix-env -iA nixpkgs.radiotray-ng'
  tags:
    - install
    - nix-packages
