- name: install node and npm - Arch
  become: true
  pacman:
    name: ['nodejs', 'npm']
    state: present
  tags:
    - install
    - node
  when: ansible_os_family == "Archlinux"

- name: install nodejs and npm - Debian
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
    - install
    - node
  when: ansible_os_family == "Debian"

- name: install nodejs and npm - macOS
  homebrew:
    name: 'node'
    state: present
  tags:
    - install
    - node
  when: ansible_distribution == "MacOSX"

- name: npmjs prefix
  shell: mkdir -p {{ home }}/.local/.npm-global
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '{{ home }}/.local/.npm-global'
  tags:
    - install
    - node

- name: install N interactive node manager
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

 # N needs to write to /usr/local/n 
 # to avoid sudo, we can own the folder
- name: create folder for n
  become: true
  shell: mkdir -p /usr/local/n
  tags:
    - install
    - node

- name: own the new folder
  become: true
  shell: chown -R {{ user }} /usr/local/n/
  tags:
    - install
    - node



- name: Install node 14
  shell: PATH={{ home }}/.local/.npm-global/bin:$PATH n 14
  tags:
    - install
    - node
