- name: install node and npm - Arch
  become: true
  pacman:
    name: ['nodejs', 'npm']
    state: present
  tags:
    - install
    - node
  when: ansible_os_family == "Archlinux"

- name: install nodejs and npm - Debian
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
    - install
    - node
  when: ansible_os_family == "Debian"

- name: install nodejs and npm - macOS
  homebrew:
    name: 'node'
    state: present
  tags:
    - install
    - node
  when: ansible_distribution == "MacOSX"

- name: create npmjs prefix folder if it doesn't exist
  file:
    path: '{{ home }}/.local/.npm-global'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '{{ home }}/.local/.npm-global'
  tags:
    - install
    - node

- name: install N interactive node manager
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

  # N needs to write to /usr/local
  # to avoid sudo, we can own the folder
- name: create folder for n if it doesn't exist
  become: true
  file:
    path: '/usr/local/n/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - node

- name: Install node 16
  shell: PATH={{ home }}/.local/.npm-global/bin:$PATH n 16
  tags:
    - install
    - node
