- name: Create folder if it doesn't exist - ~/notes
  ansible.builtin.file:
    path: '{{ home }}/notes/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - notes
  when: ansible_distribution != 'MacOSX'

- name: BUMCTrustees - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/BUMCTrustees.git'
    dest: '{{ home }}/notes/BUMCTrustees'
  tags:
    - notes
  when: ansible_distribution != 'MacOSX'

- name: Brag repo - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/brag.git'
    dest: '{{ home }}/notes/brag'
  tags:
    - notes
  when: ansible_distribution != 'MacOSX'

- name: copy notes
  copy:
    src: '../notes/notes.7z'
    dest: '{{ home }}/notes/'
    mode: 0755
    owner: '{{ user }}'
  tags:
    - notes
