# Depends on node being installed already

- name: Install Yarn
  npm:
    name: yarn
    global: true
  tags:
    - npm-packages

- name: Install eslint
  npm:
    name: eslint
    global: true
  tags:
    - npm-packages

- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: true
  tags:
    - npm-packages

- name: Install Typescript
  npm:
    name: typescript
    global: true
  tags:
    - npm-packages

- name: Install TS-Node
  npm:
    name: ts-node
    global: true
  tags:
    - npm-packages

- name: Install webpack
  npm:
    name: webpack
    global: true
  tags:
    - npm-packages

- name: Install husky
  npm:
    name: husky
    global: true
  tags:
    - npm-packages

- name: Install live-server
  npm:
    name: live-server
    global: true
  tags:
    - npm-packages

# - name: Install rimraf - used by jq
#   npm:
#     name: rimraf 
#     global: true
#   tags:
#     - npm-packages
#
# - name: Install async - used by jq
#   npm:
#     name: async 
#     global: true
#   tags:
#     - npm-packages
#
# - name: Install commander - used by jq
#   npm:
#     name: commander
#     global: true
#   tags:
#     - npm-packages
#
# - name: Install jq
#   npm:
#     name: jq
#     global: true
#   tags:
#     - npm-packages

- name: Install hueadm
  npm:
    name: hueadm
    global: true
  tags:
    - npm-packages
