# Depends on node being installed already

- name: Install Yarn
  npm:
    name: yarn
    global: true
  tags:
    - npm-packages

- name: Install eslint
  npm:
    name: eslint
    global: true
  tags:
    - npm-packages

- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: true
  tags:
    - npm-packages

- name: Install Typescript
  npm:
    name: typescript
    global: true
  tags:
    - npm-packages

- name: Install TS-Node
  npm:
    name: ts-node
    global: true
  tags:
    - npm-packages

- name: Install live-server
  npm:
    name: live-server
    global: true
  tags:
    - npm-packages

- name: Install hueadm
  npm:
    name: hueadm
    global: true
  tags:
    - npm-packages
