- name: dmenu - exists
  stat:
    path: "{{ home }}/.config/dmenu/"
  register: dmenu
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: dmenu - create folder
  shell: mkdir -p "{{ home }}/.config/dmenu/"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: dmenu.stat.exists == False

- name: dmenu - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/dmenu.git'
    dest: "{{ home }}/.config/dmenu/dmenu"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: dmenu - build and install
  become: yes
  shell: cd "{{ home }}/.config/dmenu/dmenu" && sudo make clean install
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: dmscripts - exists
  stat:
    path: "{{ home }}/.config/dmenu/dmscripts"
  register: dmscripts
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: dmscripts - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/dmscripts.git'
    dest: "{{ home }}/.config/dmenu/dmscripts"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: dmscripts.stat.exists == False

- name: dmscripts - build and install
  become: yes
  shell: cd "{{ home }}/.config/dmenu/dmscripts" && sudo make clean build install
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: slock - exists
  stat:
    path: "{{ home }}/.config/slock"
  register: slock
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: slock - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/slock.git'
    dest: "{{ home }}/.config/slock"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: slock.stat.exists == False

- name: slock - build and install
  become: yes
  shell: cd "{{ home }}/.config/slock" && sudo make clean install
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: personal scripts - exists
  stat:
    path: "{{ home }}/scripts"
  register: scripts
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: personal scripts - create folder
  shell: mkdir -p "{{ home }}/scripts"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: scripts.stat.exists == False

- name: personal scripts - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/scripts.git'
    dest: "{{ home }}/scripts/"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project


- name: wallpapers - exists
  stat:
    path: "{{ home }}/wallpapers"
  register: wallpapers 
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

- name: wallpapers - create folder
  shell: mkdir -p "{{ home }}/wallpapers"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: wallpapers.stat.exists == False

- name: wallpapers - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/wallpapers.git'
    dest: "{{ home }}/wallpapers_public/"
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project

# Extend to fetch scripts and other repos
