# - name: dmenu - exists
#   stat:
#     path: '{{ home }}/.config/dmenu/'
#   register: dmenu
#   tags:
#     - install
#     - personal-project
#
- name: dmenu - create folder if it doesn't exist
  file:
    path: '{{ home }}/.config/dmenu/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - personal-project
  # when: dmenu.stat.exists == False

- name: dmenu - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/dmenu.git'
    dest: '{{ home }}/.config/dmenu/dmenu'
  tags:
    - install
    - personal-project

- name: dmenu - build and install
  become: true
  shell:
    cmd: make clean install
    chdir: '{{ home }}/.config/dmenu/dmenu'
  tags:
    - install
    - personal-project

- name: dmscripts - exists
  stat:
    path: '{{ home }}/.config/dmenu/dmscripts'
  register: dmscripts
  tags:
    - install
    - personal-project

- name: dmscripts - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/dmscripts.git'
    dest: '{{ home }}/.config/dmenu/dmscripts'
  tags:
    - install
    - personal-project
  when: dmscripts.stat.exists == False

- name: dmscripts - build and install
  become: true
  shell:
    cmd: make clean build install
    chdir: '{{ home }}/.config/dmenu/dmscripts'
  tags:
    - install
    - personal-project

- name: slock - exists
  stat:
    path: '{{ home }}/.config/slock'
  register: slock
  tags:
    - install
    - personal-project

- name: slock - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/slock.git'
    dest: '{{ home }}/.config/slock'
  tags:
    - install
    - personal-project
  when: slock.stat.exists == False

- name: slock - build and install
  become: true
  shell:
    cmd: make clean install
    chdir: '{{ home }}/.config/slock'
  tags:
    - install
    - personal-project

- name: personal scripts - create folder if it doesn't exist
  file:
    path: '{{ home }}/scripts/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - personal-project

- name: personal scripts - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/scripts.git'
    dest: '{{ home }}/scripts/'
  tags:
    - install
    - personal-project

# - name: wallpapers - exists
#   stat:
#     path: '{{ home }}/wallpapers'
#   register: wallpapers
#   tags:
#     - install
#     - personal-project
#
- name: wallpapers - create folder if it doesn't exist
  file:
    path: '{{ home }}/wallpapers'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - personal-project
  # when: wallpapers.stat.exists == False

- name: wallpapers - clone from github
  ansible.builtin.git:
    repo: 'git@github.com:adelgado0723/wallpapers.git'
    dest: '{{ home }}/wallpapers_public/'
  tags:
    - install
    - personal-project
# Extend to fetch scripts and other repos
