- name: Install meson build system
  become: true
  ansible.builtin.pip:
    name: meson
  tags:
    - pip-packages
  when: ansible_distribution != 'MacOSX'

- name: Install ninja
  become: true
  ansible.builtin.pip:
    name: ninja
  tags:
    - pip-packages
  when: ansible_distribution != 'MacOSX'

- name: Install the AWS cli
  become: true
  ansible.builtin.pip:
    name: awscli
  tags:
    - pip-packages
