- name: Install productivity tools - Arch
  become: true
  pacman:
    name:
      - wireshark-qt
      - libreoffice-still
    state: present
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
    state: present
    update_cache: True
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: Install productivity tools - Debian
  become: true
  apt:
    name:
      - wireshark
      - libreoffice
      - poppler-utils
  tags:
    - productivity
  when: ansible_os_family == "Debian"

# - name: VSCodium - Install Snap - Debian -- Not working with live share
#   become: true
#   ansible.builtin.command: snap install codium --classic
#   tags:
#     - productivity
#   when: ansible_os_family == "Debian"

- name: altair graphql editor - Install Snap - Debian
  become: true
  ansible.builtin.command: snap install altair
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: altair graphql editor - Install from AUR - Arch
  ansible.builtin.command: paru --noconfirm -S altair
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: Postman - Install Snap - Debian
  become: true
  ansible.builtin.command: snap install postman
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: Postman - Install from AUR - Arch
  ansible.builtin.command: paru --noconfirm -S postman-bin
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: poppler (pdftoppm) - Install from AUR - Arch
  ansible.builtin.command: paru --noconfirm -S poppler
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: Install productivity tools - Common
  become: true
  ansible.builtin.package:
    name:
      - fzf
      - gimp
      - xclip
      - screenkey
      - tldr
      - ripgrep
      - maim
      - kdenlive
      - flameshot
      - jq
      - qutebrowser
      # - zoxide
    state: present
  tags:
    - productivity

- name: Install Github CLI
  become: true
  ansible.builtin.shell:
    'curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install gh -y'
  tags:
    - productivity
    - git
  when: ansible_os_family == "Debian"

- name: Install Github CLI
  become: true
  ansible.builtin.pacman:
    name: github-cli
  tags:
    - productivity
    - git
  when: ansible_os_family == "Archlinux"
