- name: Install productivity tools - Arch
  become: true
  pacman:
    name:
      - wireshark-qt
      - libreoffice-still
    state: present
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
    state: present
    update_cache: True
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: Install productivity tools - Debian
  become: true
  apt:
    name:
      - wireshark
      - libreoffice
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: VSCodium - Install Snap - Debian
  become: true
  ansible.builtin.command: snap install codium --classic
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: Install productivity tools - Common
  become: true
  ansible.builtin.package:
    name:
      - fzf
      - gimp
      - xclip
      - screenkey
      - tldr
      - ripgrep
      - maim
      - kdenlive
      - flameshot
      - qutebrowser
    state: present
  tags:
    - productivity
