- name: Install productivity tools - Arch
  become: true
  pacman:
    name:
      - wireshark-qt
      - libreoffice-still
    state: present
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: Install wireshark - Mac
  community.general.homebrew:
    name: wireshark
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - mac-setup
    - productivity

- name: Install libreoffice - Mac
  ansible.builtin.command: 'brew install --cask libreoffice'
  when: ansible_distribution == 'MacOSX'
  tags:
    - mac-setup
    - productivity

- name: Install flameshot - Mac
  ansible.builtin.command: 'brew install --cask flameshot'
  when: ansible_distribution == 'MacOSX'
  tags:
    - mac-setup
    - productivity

- name: Install gimp - Mac
  ansible.builtin.command: 'brew install --cask gimp'
  when: ansible_distribution == 'MacOSX'
  tags:
    - mac-setup
    - productivity

- name: Install xclip - Mac
  community.general.homebrew:
    name: xclip
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - mac-setup
    - productivity

- name: Install productivity tools - Debian
  become: true
  apt:
    name:
      - wireshark
      - libreoffice
      - poppler-utils
  tags:
    - productivity
  when: ansible_os_family == "Debian"

- name: poppler (pdftoppm) - Install from AUR - Arch
  ansible.builtin.command: paru --noconfirm -S poppler
  tags:
    - productivity
  when: ansible_os_family == "Archlinux"

- name: Install productivity tools - Common
  become: true
  ansible.builtin.package:
    name:
      - fzf
      - gimp
      - xclip
      - screenkey
      - tldr
      - ripgrep
      - maim
      # - flameshot
      - jq
      # - qutebrowser
      # - zoxide
    state: present
  when: ansible_distribution != "MacOSX"
  tags:
    - wsl
    - productivity

- name: Install Github CLI
  become: true
  ansible.builtin.shell:
    'curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install gh -y'
  tags:
    - wsl
    - productivity
    - git
  when: ansible_os_family == "Debian"

- name: Install Github CLI
  become: true
  ansible.builtin.pacman:
    name: github-cli
  tags:
    - wsl
    - productivity
    - git
  when: ansible_os_family == "Archlinux"

- name: Install sdkman
  ansible.builtin.command: 'curl -s "https://get.sdkman.io" | bash'
  tags:
    - wsl
    - productivity
