# prerequisite
- name: Install xcffib first
  ansible.builtin.pip:
    name:
      - xcffib
    state: present
  tags:
    - qtile
  when: ansible_os_family == "Debian"

- name: Install some dependencies - Debian
  become: true
  ansible.builtin.apt:
    name: 
      - alsa-tools
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - libffi-dev
      - libpangocairo-1.0-0
      - software-properties-common
      - libxcb-render0-dev
      - libxinerama-dev
      - python3-cairocffi
    state: present
  tags:
    - qtile
  when: ansible_os_family == "Debian"

- name: Install some dependencies -Arch
  become: true
  ansible.builtin.pacman:
    name: 
      - python
      - pango
      - python-cairocffi
      - python-xcffib
    state: present
  tags:
    - qtile
  when: ansible_os_family == "Archlinux"

- name: Install qtile from the AUR
  ansible.builtin.command: paru --noconfirm -S qtile
  tags:
    - qtile
  when: ansible_os_family == "Archlinux"

- name: Install xinerama - Arch
  ansible.builtin.pacman:
    name: libxinerama
  when: ansible_os_family == "Archlinux"


- name: Install python packages
  ansible.builtin.pip:
    name: 
      - wheel
      - pip
      - qtile
      - python-xlib
      - dbus-next
      - mypy
      - pip-install-test
    state: present
  tags:
    - qtile
  when: ansible_os_family == "Debian"

# psutil - for net widget
- name: Install psutil for net, thermal sensor, and memory widgets
  ansible.builtin.pip:
    name: psutil
  tags:
    - qtile


- name: Get stats of qtile desktop entry config
  ansible.builtin.stat:
    path: '{{ home }}/.config/qtile/qtile.desktop'
  register: desktop_config
  tags:
    - qtile

- name: Skip if no config found
  ansible.builtin.debug:
    msg: 'desktop config not found... Skipping Setup.'
  when: not desktop_config
  tags:
    - qtile

- name: Create folder if it doesn't exist - /usr/share/xsessions/
  become: true
  ansible.builtin.file:
    path: '/usr/share/xsessions/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  when: desktop_config
  tags:
    - qtile

- name: Install desktop entry
  become: true
  ansible.builtin.copy:
    src: '{{ home }}/.config/qtile/qtile.desktop'
    dest: '/usr/share/xsessions/qtile.desktop'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - qtile

- name: make link to qtile
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/qtile
    state: link
    src: '{{ home }}/.local/bin/qtile'
