- name: Dmenu - create folder if it doesn't exist
  ansible.builtin.file:
    path: '{{ home }}/.config/dmenu/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  when: ansible_distribution != 'MacOSX'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Dmenu - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/dmenu.git'
    dest: '{{ home }}/.config/dmenu/dmenu/'
  when: ansible_distribution != 'MacOSX'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Dmenu - build and install
  become: true
  ansible.builtin.command: make clean install
  args:
    chdir: '{{ home }}/.config/dmenu/dmenu'
  when: ansible_distribution != 'MacOSX'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Dmscripts - exists
  ansible.builtin.stat:
    path: '{{ home }}/.config/dmenu/dmscripts'
  register: dmscripts
  tags:
    - wsl
    - install
    - scripts-setup

- name: Dmscripts - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/dmscripts.git'
    dest: '{{ home }}/.config/dmenu/dmscripts'
  tags:
    - wsl
    - install
    - scripts-setup
  when: not dmscripts.stat.exists

- name: Dmscripts - build and install
  become: true
  ansible.builtin.command: make clean build install
  args:
    chdir: '{{ home }}/.config/dmenu/dmscripts'
  when: ansible_distribution != 'MacOSX'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Slock - exists
  ansible.builtin.stat:
    path: '{{ home }}/.config/slock'
  register: slock
  tags:
    - wsl
    - install
    - scripts-setup

- name: Slock - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/slock.git'
    dest: '{{ home }}/.config/slock'
  tags:
    - wsl
    - install
    - scripts-setup
  when: not slock.stat.exists

- name: Slock - build and install
  become: true
  ansible.builtin.command: make clean install
  args:
    chdir: '{{ home }}/.config/slock'
  when: not slock.stat.exists and ansible_distribution != 'MacOSX'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Scripts - create folder if it doesn't exist
  ansible.builtin.file:
    path: '{{ home }}/scripts/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Scripts - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/scripts.git'
    dest: '{{ home }}/scripts/'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Scripts - install
  become: true
  ansible.builtin.command: make install
  args:
    chdir: '{{ home }}/scripts/'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Wallpapers - create folder if it doesn't exist
  ansible.builtin.file:
    path: '{{ home }}/wallpapers'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Wallpapers - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/wallpapers.git'
    dest: '{{ home }}/wallpapers/wallpapers_public'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Distrotube Wallpapers - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@gitlab.com:dwt1/wallpapers.git'
    dest: '{{ home }}/wallpapers/dt_wallpapers'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Sound effects - create music folder if it doesn't exist
  ansible.builtin.file:
    path: '{{ home }}/music/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - wsl
    - install
    - scripts-setup

- name: Sound effects - clone from github
  ansible.builtin.git:
    accept_hostkey: true
    repo: 'git@github.com:adelgado0723/sounds.git'
    dest: '{{ home }}/music/sound_effects'
  tags:
    - wsl
    - install
    - scripts-setup
