- name: Slack - Snap Install - Debian
  become: true
  ansible.builtin.command: snap install slack --classic
  tags:
    - slack
  when: ansible_os_family == "Debian"

- name: Install Slack from the AUR
  ansible.builtin.command: paru --noconfirm -S slack-desktop
  tags:
    - slack
  when: ansible_os_family == "Archlinux"
