- name: Install brave
  become: true
  community.general.snap:
    name:
      - brave
    classic: true
  tags:
    - wsl
    - snap
  when: ansible_os_family == "Debian"

- name: Install kotlin
  become: true
  community.general.snap:
    name:
      - kotlin
    classic: true
  tags:
    - wsl
    - snap
