- name: Ensure .ssh directory exists.
  file:
    dest: '{{ home }}/.ssh'
    mode: 0700
    owner: '{{ user }}'
    state: directory
  tags:
    - ssh

- name: Install ssh key - id_rsa
  copy:
    src: '../.ssh/id_rsa'
    dest: '{{ home }}/.ssh/id_rsa'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key public - id_rsa
  copy:
    src: '../.ssh/id_rsa.pub'
    dest: '{{ home }}/.ssh/id_rsa.pub'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - id_rsa_2
  copy:
    src: '../.ssh/id_rsa_2'
    dest: '{{ home }}/.ssh/id_rsa_2'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - id_rsa_3
  copy:
    src: '../.ssh/id_rsa_3'
    dest: '{{ home }}/.ssh/id_rsa_3'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - belleview-microgreens
  copy:
    src: '../.ssh/belleview-microgreens'
    dest: '{{ home }}/.ssh/belleview-microgreens'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - adelg
  copy:
    src: '../.ssh/adelg'
    dest: '{{ home }}/.ssh/adelg'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh
- name: Install ssh key public - adelg
  copy:
    src: '../.ssh/adelg.pub'
    dest: '{{ home }}/.ssh/adelg.pub'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - id_rsa_vult1
  copy:
    src: '../.ssh/id_rsa_vult1'
    dest: '{{ home }}/.ssh/id_rsa_vult1'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key public - id_rsa_vult1
  copy:
    src: '../.ssh/id_rsa_vult1.pub'
    dest: '{{ home }}/.ssh/id_rsa_vult1.pub'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key - id_rsa_vult2
  copy:
    src: '../.ssh/id_rsa_vult2'
    dest: '{{ home }}/.ssh/id_rsa_vult2'
    mode: 0600
    owner: '{{ user }}'
  tags:
    - ssh

- name: Install ssh key public - id_rsa_vult2
  copy:
    src: '../.ssh/id_rsa_vult2.pub'
    dest: '{{ home }}/.ssh/id_rsa_vult2.pub'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Set authorized key took from file
  authorized_key:
    user: '{{ user }}'
    state: present
    key: '{{ item }}'
  with_file:
    - '{{ home }}/.ssh/adelg.pub'
    - '{{ home }}/.ssh/id_rsa.pub'
    - '{{ home }}/.ssh/id_rsa_vult1.pub'
    - '{{ home }}/.ssh/id_rsa_vult2.pub'
  tags:
    - ssh

- name: Install ssh config
  copy:
    src: '../.ssh/config'
    dest: '{{ home }}/.ssh/config'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Ensure git secrets directory exists.
  file:
    dest: '{{ home }}/.ssh/git/'
    mode: 0700
    owner: '{{ user }}'
    state: directory
  tags:
    - ssh

- name: Decrypt git toks
  copy:
    src: '../git/toks'
    dest: '{{ home }}/.ssh/git'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Ensure brave secrets directory exists.
  file:
    dest: '{{ home }}/.ssh/brave/'
    mode: 0700
    owner: '{{ user }}'
    state: directory
  tags:
    - ssh

- name: Decrypt brave stuff
  copy:
    src: '../brave/*'
    dest: '{{ home }}/.ssh/brave'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Copy system env file
  copy:
    src: '../env/.env'
    dest: '{{ home }}/.env'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Copy pass file
  copy:
    src: '../env/.vp.txt'
    dest: '{{ home }}/.vp.txt'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh

- name: Copy history file
  copy:
    src: '../env/.zsh_history'
    dest: '{{ home }}/.zsh_history'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - ssh
