- name: install zsh - Arch
  become: true
  pacman:
    name: 'zsh'
    state: present
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']
  when: ansible_os_family == "Archlinux"

- name: install zsh - Debian
  become: true
  apt:
    name: 'zsh'
  tags: *tags_for_zsh_tasks
  when: ansible_os_family == "Debian"

- name: change shell to zsh
  become: true
  #  shell: chsh -s $(chsh -l | grep zsh | sort -r | awk '(NR == 1){print $1}')
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: check if ~/.oh-my-zsh/ exists
  stat:
    path: '{{ home }}/.oh-my-zsh'
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: install oh my zsh
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '{{ home }}/.oh-my-zsh'
    depth: 1
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False


- name: install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags: *tags_for_zsh_tasks

- name: install fzf-tab
  ansible.builtin.git:
    repo: 'https://github.com/Aloxaf/fzf-tab.git'
    dest: '{{ home }}/.oh-my-zsh/plugins/fzf-tab'
  tags: *tags_for_zsh_tasks
